myweb/artikel/urls.py
from django.conf.urls import url

from .views import (ArtikelListView,ArtikelDetailView,ArtikelKategoriListView,ArtikelCreateView,ArtikelManageView,ArtikelDeleteView,ArtikelUpdateView)





urlpatterns = [
url(r'^manage/update/(?P<pk>\d+)$', ArtikelUpdateView.as_view(), name='update'),
url(r'^manage/delete/(?P<pk>\d+)$', ArtikelDeleteView.as_view(), name='delete'),
url(r'^manage/$', ArtikelManageView.as_view(), name='manage'),
url(r'^tambah/$', ArtikelCreateView.as_view(), name='create'),
url(r'^kategori/(?P<kategori>[\w]+)$', ArtikelListView.as_view(),name='category' ),
url(r"^detail/(?P<slug>[\w-]+)$", ArtikelDetailView.as_view(), name="detail"),
    
url(r'^(?P<page>\d+)$', ArtikelListView.as_view(), name="list"),
]

myweb/myweb/urls.py

from django.contrib import admin
from django.conf.urls import url, include

from django.views.generic import TemplateView


from .views import BlogHomeView
urlpatterns = [
    url(r'^artikel', include('artikel.urls', namespace='artikel')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', BlogHomeView.as_view(), name='home'),
]

myweb/artikel/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
#creat your models here

class Artikel(models.Model):
  judul = models.CharField(max_length=255)
  isi = models.TextField()
  kategori = models.CharField(max_length=255)
  published = models.DateTimeField(auto_now_add=True)
  update = models.DateTimeField(auto_now=True)
  slug = models.SlugField(blank=True, editable=False)

  def save(self):
    self.slug = slugify(self.judul)
    super().save()

  def get_absolute_url(self):
      url_slug = {'slug':self.slug}
      return reverse("artikel:detail", kwargs=url_slug)
  

  def __str__(self):
    return "{}. {}".format(self.id, self.judul)



myweb/artikel/forms.py
from django.forms import ModelForm

from .models import Artikel


class ArtikelForm(ModelForm):
  class Meta:
    model = Artikel
    fields = [
    'judul',
    'isi',
    'kategori',
    
    ]

myweb/artikel/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Artikel
# Create your views here.
from .forms import ArtikelForm



class ArtikelUpdateView(UpdateView):
  form_class = ArtikelForm
  model = Artikel
  template_name = "artikel/artikel_Update.html"




class ArtikelDeleteView(DeleteView):
  model = Artikel
  template_name = "artikel/artikel_delete_confirmation.html"
  success_url = reverse_lazy('artikel:manage')




class ArtikelManageView(ListView):
  model = Artikel
  template_name = "artikel/artikel_manage.html"
  context_object_name = 'artikel_list'



class ArtikelCreateView(CreateView):
  form_class = ArtikelForm
  template_name = "artikel/artikel_create.html"

class ArtikelPerKategori():
  model = Artikel


  def get_latest_artikel_each_kategori(self):
    kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
    queryset = []

    for kategori in kategori_list:
      artikel = self.model.objects.filter(kategori=kategori).latest('published')
      queryset.append(artikel)

    return queryset




class ArtikelKategoriListView(ListView):
  model = Artikel
  template_name = "artikel/artikel_katagori_list.html"
  context_object_name = 'artikel_list'
  ordering = ['-published']
  paginate_by = 3




  def get_queryset(self):
    self.queryset = self.model.objects.filter(kategori=self.kwargs['kategori'])
    return super().get_queryset()

  def get_context_data(self,*args,**kwargs):
    kategori_list = self.model.objects.values_list('kategori', flat=True).distinct().exclude(kategori=self.kwargs['kategori'])
    self.kwargs.update({'kategori_list' :kategori_list})
    kwargs = self.kwargs
    return super().get_context_data(*args,**kwargs)

class ArtikelListView(ListView):
  model = Artikel
  template_name= "artikel/artikel_list.html"
  context_object_name = 'artikel_list'
  ordering = ['-published']
  paginate_by = 3

  def get_context_data(self,*args,**kwargs):
      kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
      self.kwargs.update({'kategori_list' :kategori_list})
      kwargs = self.kwargs
      return super().get_context_data(*args,**kwargs)


class ArtikelDetailView(DetailView):
  model = Artikel
  template_name = "artikel/artikel_detail.html"
  context_object_name = 'artikel'

myweb/myweb/views.py
from multiprocessing import context
from artikel.models import Artikel
from django.views.generic import TemplateView


from artikel.views import ArtikelPerKategori

class BlogHomeView(TemplateView, ArtikelPerKategori):
  template_name = "index.html"

  def get_context_data(self):
    querysets = self.get_latest_artikel_each_kategori()
    context = {
      'latest_artikel_list':querysets,
    }

    return context

myweb/artikel/templates/artikel/artikel_create.html
{% extends 'base.html' %} {% block page_title %} Create {% endblock page_title %} {% block contents %}
<h1>Tambah Artikel</h1>
<form method="POST">
  {% csrf_token %}

  <div class="form-group">
    <label for="{{form.judul.id_for_label}}">{{form.judul.label}}:</label>
    <input type="text" class="form-control" name="{{form.judul.name}}" maxlength="{{form.judul.max}}" required id="{{form.judul.id_for_label}}" />
  </div>

  <div class="form-group">
    <label for="{{form.isi.id_for_label}}">{{form.isi.label}}:</label>
    <textarea class="form-control" name="{{form.isi.name}}" rows="10" required id="{{form.isi.id_for_label}}"></textarea>
  </div>

  <div class="form-group">
    <label for="{{form.kategori.id_for_label}}">{{form.kategori.label}}:</label>
    <input type="text" class="form-control" name="{{form.kategori.name}}" maxlength="{{form.kategori.max}}" required id="{{form.kategori.id_for_label}}" />
  </div>

  <button type="submit" class="btn btn-primary">Tambah</button>
</form>

{% endblock contents %}

myweb/artikel/templates/artikel/artikel_delete_confirmation.html
{% extends 'base.html' %} {% block page_title %} Delete artikel {% endblock page_title %} {% block contents %}
<h1>Delete Artikel Confirmation</h1>
<p>Apakah benar anda ingin menghapus artikel berikut:</p>
<h3>{{artikel.judul}}</h3>
<p>{{artikel.published}}</p>
<form method="POST">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-primary">Ya</button>
  <a class="btn btn-outline-danger" href="{% url 'artikel:manage' %}">Tidak</a>
</form>
{% endblock contents %}

myweb/artikel/templates/artikel/artikel_detail.html
{% extends 'base.html' %} {% block page_title %} {{artikel.judul}} {% endblock page_title %} {% block contents %}
<h1>{{artikel.judul}}</h1>
<h5>Kategori: {{artikel.kategori}} | {{artikel.published}}</h5>

<p>{{artikel.isi}}</p>
{% endblock contents %}

myweb/artikel/templates/artikel/artikel_kategori_list.html
{% extends 'base.html' %}

{% block page_title %}
 Artikel 
 {% endblock page_title %} 
 {% block contents %}
 

<div class="row">
  <div class="col-md-8">
    <h2>Kategori: {{kategori}}</h2>


          {% if is_paginated %}
      <nav aria-label="artikelpage">
        <ul class="pagination">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="{% url 'artikel:list'  page_obj.previous_page_number %}">Previous</a>
          </li>

          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
          {% endif %} {% for page in paginator.page_range %} {% if page is page_obj.number %}
          <li class="page-item active" aria-current="page">
            <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
          </li>
          {% else %}
          <li class="page-item"><a class="page-link" href="{% url 'artikel:list' page %}">{{page}}</a></li>
          {% endif %} {% endfor %} {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="{% url 'artikel:list'  page_obj.next_page_number %}">Next</a>
          </li>
          {% endif %}
        </ul>
      </nav>

      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
        {% endif %} {% for artikel in artikel_list %}

        <h3><a class="text-dark" href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
        <p>Kategori: {{artikel.kategori}} | {{artikel.published}}</p>

        <p>{{artikel.isi|truncatewords:10}} <a href="{% url 'artikel:detail' artikel.slug %}"> selengkapnya</a></p>

        {% endfor %}
  </div>
  <div class="col-sm">
    <h3>Kategori lainnya</h3>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><a href="{% url 'artikel:list' 1 %}">Semua Kategori</a></li>
      {% for kategori in kategori_list  %}
      <li class="list-group-item"><a href="{% url 'artikel:category' kategori %}">{{kategori}}</a></li>


      
     
    </ul>
  </div>




</div>

{% endblock contents %}
</li>

myweb/artikel/templates/artikel/artikel_list.html
{% extends 'base.html' %} 
{% block page_title %}
 Artikel 
 {% endblock page_title %} 
 {% block contents %}
 

<div class="row">
  <div class="col-md-8">
          {% if is_paginated %}
      <nav aria-label="artikelpage">
        <ul class="pagination">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="{% url 'artikel:list'  page_obj.previous_page_number %}">Previous</a>
          </li>

          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
          {% endif %} {% for page in paginator.page_range %} {% if page is page_obj.number %}
          <li class="page-item active" aria-current="page">
            <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
          </li>
          {% else %}
          <li class="page-item"><a class="page-link" href="{% url 'artikel:list' page %}">{{page}}</a></li>
          {% endif %} {% endfor %} {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="{% url 'artikel:list'  page_obj.next_page_number %}">Next</a>
          </li>
          {% endif %}
        </ul>
      </nav>

      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
        {% endif %} {% for artikel in artikel_list %}

        <h3><a class="text-dark" href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
        <p>Kategori: {{artikel.kategori}} | {{artikel.published}}</p>

        <p>{{artikel.isi|truncatewords:10}} <a href="{% url 'artikel:detail' artikel.slug %}"> selengkapnya</a></p>

        {% endfor %}
  </div>
  <div class="col-sm">
    <h3>Kategori</h3>
    <ul class="list-group list-group-flush">
      {% for kategori in kategori_list  %}
         <li class="list-group-item"><a href="{% url 'artikel:category' kategori %}">{{kategori}}</a></li>

      {% endfor %}


      
     
    </ul>
  </div>




</div>

{% endblock contents %}
</li>

myweb/artikel/templates/artikel/artikel_manage.html
{% extends 'base.html' %} {% block page_title %} Manage Artikel {% endblock page_title %} {% block contents %}
<h1>Manage Artikel</h1>
<a class="btn btn-primary btn-block" href="{% url 'artikel:create' %}">Tambah Artikel</a>

<table class="table mt-4">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Judul</th>
      <th scope="col">Kategori</th>
      <th scope="col">Published</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for artikel in artikel_list %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{artikel.judul}}</td>
      <td>{{artikel.kategori}}</td>
      <td>{{artikel.published}}</td>
      <td>
        <a class="btn btn-warning" href="{% url 'artikel:update' artikel.id %}">Edit</a>
        <a class="btn btn-danger" href="{% url 'artikel:delete' artikel.id %}">Delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock contents %}

myweb/artikel/templates/artikel/artikel_update.html
{% extends 'base.html' %} {% block page_title %} Update{% endblock page_title %} {% block contents %}
<h1>Update Artikel</h1>
<form method="POST">
  {% csrf_token %}

  <div class="form-group">
    <label for="{{form.judul.id_for_label}}">{{form.judul.label}}:</label>
    <input type="text" class="form-control" name="{{form.judul.name}}" maxlength="{{form.judul.max}}" required id="{{form.judul.id_for_label}}" value="{{form.judul.value}}" />
  </div>

  <div class="form-group">
    <label for="{{form.isi.id_for_label}}">{{form.isi.label}}:</label>
    <textarea class="form-control" name="{{form.isi.name}}" rows="10" required id="{{form.isi.id_for_label}}">{{form.isi.value}}</textarea>
  </div>

  <div class="form-group">
    <label for="{{form.kategori.id_for_label}}">{{form.kategori.label}}:</label>
    <input type="text" class="form-control" name="{{form.kategori.name}}" maxlength="{{form.kategori.max}}" required id="{{form.kategori.id_for_label}}" value="{{form.kategori.value}}" />
  </div>

  <button type="submit" class="btn btn-warning">update</button>
  <a href="{% url 'artikel:manage' %}" class="btn btn-danger">Tidak</a>
</form>

{% endblock contents %}

myweb/templates/base.html
{% load static %}

<html>
  <head>
    <title>{% block page_title %} {% endblock page_title %}</title>
    {% include "snippets/styles.html" %}
  </head>
  <body>
    {% include "snippets/navbar.html" %}

    <div class="container" style="margin-top: 100px">{% block contents %} {% endblock contents %}</div>

    {% include "snippets/scripts.html" %}
  </body>
</html>

myweb/templates/index.html
{% extends 'base.html' %} {% block page_title %} Home {% endblock page_title %} {% block contents %}
<h1>Home</h1>
<div class="row">
  {% for artikel in latest_artikel_list %}
  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'artikel:category' artikel.kategori %}">{{artikel.kategori}}</a></h5>
        <h6 class="card-subtitle mb-2 text-muted">{{artikel.judul}}</h6>
        <p class="card-text">{{artikel.isi|truncatewords:10}}</p>
        <a href="{% url 'artikel:detail' artikel.slug %}" class="card-link">Selengkapnya</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock contents %}

myweb/templates/snippets/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Inspiration</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'artikel:list' 1 %}">Artikel</a>
        </li>
      </ul>
      <div class="nav-item dropdown ml-auto">
        <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-toggle="dropdown" aria-expanded="false"> User</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'artikel:create' %}">Tambah artikel</a>
          <a class="dropdown-item" href="{% url 'artikel:manage' %}">Manage artikel</a>
        </div>
      </div>
    </div>
  </div>
</nav>

myweb/templates/snippets/scripts.html
{% load static %}
<script src="{% static 'vendor/jquery/jquery-3.6.0.min.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/boostrap/js/bootstrap.min.js' %}" type="text/javascript"></script>

myweb/templates/snippets/styles.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vendor/boostrap/css/bootstrap.min.css' %}" />